### ISSUE TITLE
Turing_test 

### ISSUE THREAD

**Issue by adityajain28** [ImagingLab/Colorizing-with-GANs#10]
I am running turing_test on my own dataset using places365 dataset as specified. I am able to train the model but when running turing_test, it gives me this error:
"ValueError: Trying to share variable gen/conv0/kernel, but specified shape (4, 4, 1, 64) and found shape (4, 4, 4, 64)."

I assume this is regarding the kernel size and the input image dimensions, but I am able to solve it as of now.
Any help will be appreciated.

**Comment by adityajain28** [comment]
![untitled](https://user-images.githubusercontent.com/19147940/49334376-7f0f0d00-f5a2-11e8-9108-05a9e08f9c80.png)

**Comment by knazeri** [comment]
@adityajain28 For the Turing test, the idea is to use human judgment to compare a colored image with the ground truth. Having said that, you need to provide RGB image as input. The model automatically extracts the grayscale from the RGB image and feed it to the model. My guess is that in your test dataset you are providing the grayscale image as input and that's why you are getting tensor mismatch error.

We understand the need for a test method that runs on a grayscale image and we are going to implement one in just a few days.

**Comment by adityajain28** [comment]
What does the sampler do then? The error comes in the Conv2D method. I gave the RBG image in feed dict and input_gray in the sampler, but still I get the same error.

**Comment by adityajain28** [comment]
What does the sampler do then? The error comes in the Conv2D method. I gave the RBG image in feed dict and input_gray in the sampler, but still I get the same error.

**Comment by knazeri** [comment]
The Sampler is the same as the generator, in fact, it reuses the generator parameters and is used for evaluation only (you can set it to run on a different GPU for example). The input to the Sampler has to be exactly as the generator. We used Sampler for visualization purposes.

**Comment by knazeri** [comment]
@adityajain28 We have implemented a test procedure to evaluate the model on custom image(s)
https://github.com/ImagingLab/Colorizing-with-GANs#test
