### ISSUE TITLE
IndexError while executing test-eval.py

### ISSUE THREAD

**Issue by apatki1996** [ImagingLab/Colorizing-with-GANs#8]
I have downloaded the pre-trained weights in the checkpoints and I am executing the test-eval.py code on a cluster. I am facing the following error.

![screenshot from 2018-10-23 20-10-11](https://user-images.githubusercontent.com/22829792/47399683-b965ce80-d707-11e8-8c9a-55e63cec4aeb.png)

**Comment by rmrafailov** [comment]
I've had the same error when trying to run on AWS. Did you manage to resolve it?

**Comment by apatki1996** [comment]
Ok, Thanks! I will look into it.

**Comment by knazeri** [comment]
@apatki1996 The problem was printing the metrics after evaluation. This was caused by how different versions of numpy implement mean of an array of tuples! This line was the problem:
https://github.com/ImagingLab/Colorizing-with-GANs/blob/5d2a976710de4e5aabd32fcf6e32519bca1729e4/src/models.py#L112

I changed the implementation, so that the metrics would be printed as evaluating. Please confirm if the is resolved.
